access_key_id: ENC[AES256_GCM,data:3u2pTZT69q++h6pLI4KeXJq/Wvw=,iv:BewgmA9QzavG8E7DQSo4r3GOirEWbuHhqzDQom81BQo=,tag:mPITtz243KbmS87o6eLtYQ==,type:str]
secret_access_key: ENC[AES256_GCM,data:butk4BtCC3THVhFdBBuWQY/jV4dsypQ824DnGbUa0zNjN7Tl0OJkeg==,iv:Om0kQIa9V9ayHUVa9yJ1/KTkc4KuF27+E2rHqrzeOmc=,tag:mjI3TpCPsH19hsYZWvCEWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-08T14:44:58Z"
    mac: ENC[AES256_GCM,data:rpyDNsVIcwayxBuKPg2seDtM8b1mexLH/PvHKHbJM2QClTjwIi9ZGVXBcSxERabwf96+HQS+lbgCyoYeSWkIVkhoygmvh9hMwE88dYSsRvHr8U+KRC8ZIdQgTmLvCIRw4g9de4WmmgFi2yHU6UbIQbYrQdaHG8uvEkddtAMME2w=,iv:NNFCzBbVqBbfEfkLb8xFQpqx+gNigCKO+BhoDco/C6A=,tag:kBKBaYUZf5OGS6WqvDkQXg==,type:str]
    pgp:
        - created_at: "2023-06-08T14:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6R1jsw7jFIKAQwAlTx9x5lwB/JKVYy1n+wenhrN7/Gh/j3T1Ulyp2XiM7A8
            FpIxSrCbvXOomNohbbtlyUCvjQJPsYpdnlioObTuGzeL6RXKIMyehdps5R+N3jnD
            BsMWL7avdrtDagYnM/91C/MkQWnb3wqwG92lwWey5EnQOTVoD2sLaC0d1zEQESeA
            xomu2+quBgkwftrYaxanhMMRlAyUN1UUPepwlLAzsTiQzRU9WM5cT+BVGlVbNbE5
            khmxjrRuHM5jMNSeLiz9U/dZ6n6mlFNJan4MxTJGtTg/wcHF3KOUD5zsijjq7v27
            JO8yyE2M9atvT2oTdlb24Nu9NE20RGXy0O6wx6YJzjJ/r8bYIglVhJTb6DV3whw0
            75vavyC3koJ7DoDVeZFfKvzSQ/ibg+QVRmruU0Wa8e6L3eKfuSB7nDFhJ+FXAF9A
            BTl2881tpfacK6DCvuiYkKx7pAqQVB0mMTMt8mSkxk5AxADyrMNrUWlo4+QlSDsa
            KefavCcv6KVawopZ5Ra+0lwBGYZpD4lLEnslFnhvoI2r1kRj9a9i385uOJn2gQzi
            52OGtOmgZQ354+EySyu/UzI0mPjyYnVYwBiZcE8+UPuKkUpW/iE71GhzeiwoqBuP
            Nj39x4J8suEtR8hW8Q==
            =AJtK
            -----END PGP MESSAGE-----
          fp: 05590021BE8B2A6174BEEE002F8A9D86D3C5BAA2
    unencrypted_suffix: _unencrypted
    version: 3.7.3
