AWS_DEFAULT_REGION: ENC[AES256_GCM,data:0AQ9+fSIQLRGBSr1,iv:an/LyYzwuLCvERHCA9bi9vz9XxcGfnt/j+rXw+IBaI4=,tag:HpuRNRjeFPeq7NWVXkbdpA==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Dnb0r+V+BdmitL09kgkXTkyky9E=,iv:ZREyJ1EL30B2DC2wk5MrNKw5ftN5uND95LDY5mw47PY=,tag:RDygpT/GGF2Q3QcrkiaF8g==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uJHv2sJKUzB2EMMMFKQrnQ2dKnFYvED3BL11hNFBAGs9yEurkwhq7Q==,iv:YlV401Jwr0rsiWmHobSfPEJPK+fFccjzPgKUbJTe8fg=,tag:wyIvG2aKfJpV5GsK98GGgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-08T15:42:29Z"
    mac: ENC[AES256_GCM,data:nelDSfCuIqWSy5tGMu9pYbkb4g0+R2vCou6MVMphzyisiqoja3ZSwSaPxD0Q6o+ttph+ruj1E+x6LNLzaCGGBeH4Wq5fWHcrFh8wHKIiaEmpCeHreu/phu4P4r1JACPoz+b1Xi76aGXh2p8a9DNZFTfRaiPpG8DAW5nsiQERw7o=,iv:1sXrudBncnt2hDwkLtyV/dMaiB5JNWwrW2o8GcwCSlU=,tag:bgSLC33+1CsnjZcY6Tk7Tg==,type:str]
    pgp:
        - created_at: "2023-06-08T14:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6R1jsw7jFIKAQwAlTx9x5lwB/JKVYy1n+wenhrN7/Gh/j3T1Ulyp2XiM7A8
            FpIxSrCbvXOomNohbbtlyUCvjQJPsYpdnlioObTuGzeL6RXKIMyehdps5R+N3jnD
            BsMWL7avdrtDagYnM/91C/MkQWnb3wqwG92lwWey5EnQOTVoD2sLaC0d1zEQESeA
            xomu2+quBgkwftrYaxanhMMRlAyUN1UUPepwlLAzsTiQzRU9WM5cT+BVGlVbNbE5
            khmxjrRuHM5jMNSeLiz9U/dZ6n6mlFNJan4MxTJGtTg/wcHF3KOUD5zsijjq7v27
            JO8yyE2M9atvT2oTdlb24Nu9NE20RGXy0O6wx6YJzjJ/r8bYIglVhJTb6DV3whw0
            75vavyC3koJ7DoDVeZFfKvzSQ/ibg+QVRmruU0Wa8e6L3eKfuSB7nDFhJ+FXAF9A
            BTl2881tpfacK6DCvuiYkKx7pAqQVB0mMTMt8mSkxk5AxADyrMNrUWlo4+QlSDsa
            KefavCcv6KVawopZ5Ra+0lwBGYZpD4lLEnslFnhvoI2r1kRj9a9i385uOJn2gQzi
            52OGtOmgZQ354+EySyu/UzI0mPjyYnVYwBiZcE8+UPuKkUpW/iE71GhzeiwoqBuP
            Nj39x4J8suEtR8hW8Q==
            =AJtK
            -----END PGP MESSAGE-----
          fp: 05590021BE8B2A6174BEEE002F8A9D86D3C5BAA2
    unencrypted_suffix: _unencrypted
    version: 3.7.3
