version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  build:
    docker:
      - image: cimg/aws:2023.06

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.17

workflows:
    example-workflow:
      jobs:
        - aws-ecr/build-and-push-image:
            assume-web-identity: false 
            aws-cli-version: latest 
            repo: website_github_cricle-ci 
            setup-remote-docker: true 
            tag: $(TZ="Europe/Warsaw" date '+%Y-%m-%d-%H-%M-%S') 
            repo-scan-on-push: true
            push-image: true 