version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    parameters:
      env:
        type: string
      docker_cache:
        type: boolean
        default: true
      push_image:
        type: boolean
        default: true
    docker:
      - image: cimg/aws:2022.10
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: << parameters.env >>-frontend
          registry-id: AWS_ACCOUNT_ID
          setup-remote-docker: true
          tag: "${CIRCLE_SHA1}"
          remote-docker-layer-caching: << parameters.docker_cache >>
          push-image: << parameters.push_image >>
