version: 2.1
jobs:
  build:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - run:
          name: Build and Push Docker Image
          command: |
            aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 327471327668.dkr.ecr.eu-central-1.amazonaws.com
            docker build -t website_github_cricle-ci .
            docker tag website_github_cricle-ci:latest 327471327668.dkr.ecr.eu-central-1.amazonaws.com/website_github_cricle-ci:$(TZ="Europe/Warsaw" date '+%Y-%m-%d-%H-%M-%S')
            docker push 327471327668.dkr.ecr.eu-central-1.amazonaws.com/website_github_cricle-ci:$(TZ="Europe/Warsaw" date '+%Y-%m-%d-%H-%M-%S')