version: 2.1
jobs:
  build:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - run:
          name: Build and Push Docker Image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 327471327668.dkr.ecr.us-east-1.amazonaws.com
            docker build -t website_frontend .
            docker tag website_frontend:latest 327471327668.dkr.ecr.us-east-1.amazonaws.com/website_frontend:latest
            docker push 327471327668.dkr.ecr.us-east-1.amazonaws.com/website_frontend:latest