version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
    example-workflow:
      jobs:
        - aws-ecr/build-and-push-image:
            assume-web-identity: false 
            aws-cli-version: latest 
            repo: website_github_cricle-ci 
            setup-remote-docker: true 
            tag: $(TZ="Europe/Warsaw" date '+%Y-%m-%d-%H-%M-%S') 
            repo-scan-on-push: true 
            registry-id: '327471327668' 
            push-image: true 